worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    # Serwer dla Angulara
    server {
        listen 80;
        server_name 192.168.100.237;
        return 301 https://$host$request_uri;  # Redirect HTTP to HTTPS
    }

    # Serwer HTTPS (jeśli potrzebujesz)
    server {
        listen 443 ssl;
        server_name 192.168.100.237;

        ssl_certificate /etc/nginx/certs/fullchain.pem;
        ssl_certificate_key /etc/nginx/certs/privkey.pem;

        location /tictoe/ {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /tictoe/index.html;
        }

        location / {
            proxy_pass https://keycloak:8443/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /tictoe-backend/ {
            proxy_pass http://tictoe-backend:8080/tictoe-backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /dev/ {
            # Tutaj nie robimy nic z aplikacją Angular
            # Angular serwuje swoje zasoby na porcie 4200
        }
    }
}
